### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by TheArtemMaps** [shockpast/gm_discord_rpc#1]
gm_discord_rpc.lua:22: 'then' expected near 'return'
    1. unknown - lua/menu/menu.lua:22
        2. include - [C]:-1
            3. unknown - lua/includes/menu.lua:9

**Comment by shockpast** [comment]
@TheArtemMaps, new [commit ](https://github.com/shockpast/gm_discord_rpc/commit/d50d51d47b9552fb84ddbfcc4fc4a52a6b06098f) is published with fix, is it working for you?

**Comment by TheArtemMaps** [comment]
> @TheArtemMaps, new [commit ](https://github.com/shockpast/gm_discord_rpc/commit/d50d51d47b9552fb84ddbfcc4fc4a52a6b06098f) is published with fix, is it working for you?

yep, it's working now, thank you!
